### ISSUE TITLE
Problem runnig pgzabbix on Ubuntu 10.10 (python problem)

### ISSUE THREAD

**Issue by bilbolodz** [Spindel/PgZabbix#4]
When I'm trying to run pgzabbix on Ubuntu 10.10 I'm getting an error:

'
root@pse:~# /usr/bin/python /usr/local/lib/pgzabbix-1.7.linux-x86_64.zip --read
\- psql.running 1
\- psql.primary_server 1
[..]
\- psql.server_maxcon 100
Traceback (most recent call last):
  File "/usr/lib/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/usr/local/lib/pgzabbix-1.7.linux-x86_64.zip/__main__.py", line 4, in <module>
  File "/usr/local/lib/pgzabbix-1.7.linux-x86_64.zip/pgzabbix/cmd.py", line 59, in main
    prototypes that will later be wrapped in a more sophisticated interface.
  File "/usr/local/lib/pgzabbix-1.7.linux-x86_64.zip/pgzabbix/__init__.py", line 35, in all_generic
  File "/usr/local/lib/pgzabbix-1.7.linux-x86_64.zip/pgzabbix/generic.py", line 71, in psql_slow_dml_queries
ValueError: zero length field name in format
'

**Comment by Spindel** [comment]
Ubuntu 10.10 is approaching 9 years old, and past the time limit that I'm willing to spend massaging code as a hobby.

I'll gladly take patches if you figure it out, otherwise I'd recommend running your data collector on another machine.

**Comment by bilbolodz** [comment]
It's probably problem with python 2.6 version and changes with format function:
https://stackoverflow.com/questions/10054122/valueerror-zero-length-field-name-in-format-python
https://pyformat.info/

**Comment by bilbolodz** [comment]
I've finished fixes for python 2.6. I will test it and publish.
